In [1]:
import pandas as pd
from pandas import DataFrame

In [3]:
a = DataFrame([[1,2,3], [2,3,4]], columns=["a", "b", "c"])
a.head()

a  b  c
0  1  2  3
1  2  3  4

In [4]:
a.loc[0]

a    1
b    2
c    3
Name: 0, dtype: int64

In [1]:
import src.main as main
import src.params as params
import src.model as model
import src.stats as stats
import importlib
importlib.reload(model)
importlib.reload(params)
importlib.reload(main)
importlib.reload(stats)
args = params.get_args("../config/basic.yaml")
data = main.get_cmdb(args)
args = params.get_args("../config/basic.yaml")
smodel = model.Statistic(args, data)

Loading preprocessed data from /home/junetheriver/code/aiops/workdir/system_a/data_pre.pkl


In [15]:
smodel.std

array([[9.24274339e-01],
       [4.51798696e-03],
       [7.25080752e+05],
       ...,
       [5.08733824e-01],
       [4.19040857e+02],
       [9.56942976e-03]])

In [2]:
dataset = main.get_dataset(args)

In [3]:
trainset, validset, testset = dataset

In [4]:
x, y = trainset[0]

In [5]:
x

('gjjcore9', Timestamp('2021-02-26 23:27:18.533989'))

In [6]:
y

2

In [35]:
model.get_kpi_at_time(smodel.data, x[1])

array([1.000000e-01, 1.000000e-02, 3.249431e+06, ..., 0.000000e+00,
       8.575000e+03, 4.000000e-02])

In [48]:
importlib.reload(model)
smodel = model.Statistic(args, data)
smodel.forward(x)

tensor([0.1415, 0.0935, 0.1515, 0.0874, 0.1663, 0.1321, 0.1046, 0.1231],
       grad_fn=<SoftmaxBackward0>)

In [23]:
import numpy as np
importlib.reload(model)

<module 'src.model' from '/home/junetheriver/code/aiops/src/model.py'>

In [18]:
for x, y in trainset:
    # print(x)
    print(model.get_kpi_at_time(smodel.data, x[1]))

[0.0000000e+00 2.0000000e-02 2.2018905e+06 ... 0.0000000e+00 8.1040000e+03
 3.0000000e-02]
[1.900000e-01 1.000000e-02 4.302191e+06 ... 0.000000e+00 7.758000e+03
 1.000000e-02]
[0.0000000e+00 1.0000000e-02 3.5341305e+06 ... 0.0000000e+00 7.4080000e+03
 2.0000000e-02]
[0.00000e+00 1.00000e-02 4.27429e+06 ... 0.00000e+00 7.76400e+03
 1.00000e-02]
[2.0000000e-02 1.0000000e-02 3.1954305e+06 ... 0.0000000e+00 8.5540000e+03
 1.0000000e-02]
[nan nan nan ... nan nan nan]
[0.00000000e+00 1.00000000e-02 3.74143025e+06 ... 0.00000000e+00
 7.50000000e+03 1.00000000e-02]
[0.00000000e+00 2.00000000e-02 2.13361025e+06 ... 0.00000000e+00
 8.05200000e+03 2.00000000e-02]
[0.000000e+00 1.000000e-02 3.458831e+06 ... 0.000000e+00 7.399000e+03
 3.000000e-02]
[0.00000000e+00 1.00000000e-02 3.39805025e+06 ... 0.00000000e+00
 8.67900000e+03 1.00000000e-02]
[0.00000000e+00 2.00000000e-02 2.19331025e+06 ... 0.00000000e+00
 8.08600000e+03 2.00000000e-02]
[0.00000000e+00 1.00000000e-02 3.29611075e+06 ... 0.00000000

KeyboardInterrupt: 

In [19]:
x

('gjjcore8', Timestamp('2021-03-11 02:26:02.491145'))

In [42]:
smodel.forward(x)

tensor([ 0.0627, -0.6325, -0.0501,  ..., -0.1229,  1.6004,  2.3880])
tensor([nan, nan, nan, nan, nan, nan, nan, nan], grad_fn=<ReluBackward0>)


tensor([nan, nan, nan, nan, nan, nan, nan, nan], grad_fn=<SoftmaxBackward0>)

In [36]:
a = np.array([1,2,3])
b = np.array([1,1,1])
c = np.subtract(a, b)
print(c)

[0 1 2]


In [41]:
smodel.train()

Statistic(
  (fc): Linear(in_features=2152, out_features=8, bias=True)
)